const fs = require('fs');
const path = require('path');
const ICON_DIR = path.join(process.env.HOME, 'Developer/storico/frontend/node_modules/lucide-react/dist/esm/icons');
const NAMES = [
  'alert-circle', 'arrow-left', 'building-2', 'check', 'check-circle-2', 'chevron-down',
  'chevron-right', 'chevrons-up-down', 'circle-user', 'file-text', 'fingerprint',
  'folder-kanban', 'grip-vertical', 'house', 'kanban-square', 'languages', 'layout-dashboard', 'list-tree',
  'loader-2', 'log-out', 'moon', 'panel-left', 'pencil', 'plus', 'search', 'settings',
  'sparkles', 'sun', 'trash-2', 'upload', 'user',
];
function literal(src, file) {
  const start = src.indexOf('const __iconNode = ');
  if (start === -1) return null;
  const i = src.indexOf('[', start);
  let depth = 0, quote = null;
  for (let j = i; j < src.length; j++) {
    const c = src[j];
    if (quote) { if (c === '\\') { j++; continue; } if (c === quote) quote = null; continue; }
    if (c === '"' || c === "'" || c === '`') { quote = c; continue; }
    if (c === '[') depth++;
    else if (c === ']') { depth--; if (depth === 0) return src.slice(i, j + 1); }
  }
  throw new Error('unbalanced in ' + file);
}
function resolveNodes(name, seen = new Set()) {
  if (seen.has(name)) throw new Error('alias cycle at ' + name);
  seen.add(name);
  const file = path.join(ICON_DIR, name + '.js');
  if (!fs.existsSync(file)) return null;
  const src = fs.readFileSync(file, 'utf8');
  const lit = literal(src, name);
  // lucide's node arrays are JS object literals (unquoted keys), not JSON.
  if (lit) return new Function('return ' + lit)();
  const m = src.match(/export \{ default \} from '\.\/([^']+)\.js'/);
  if (m) return resolveNodes(m[1], seen);
  throw new Error('cannot read nodes from ' + name);
}
const esc = (s) => String(s).replace(/&/g, '&amp;').replace(/"/g, '&quot;').replace(/</g, '&lt;');
const entries = [];
for (const name of NAMES) {
  const nodes = resolveNodes(name);
  if (!nodes) throw new Error('missing icon: ' + name);
  const inner = nodes.map(([tag, attrs]) => {
    const a = Object.entries(attrs).filter(([k]) => k !== 'key')
      .map(([k, v]) => ` ${k}="${esc(v)}"`).join('');
    return `<${tag}${a}/>`;
  }).join('');
  entries.push([name, inner]);
}
const out = `/**
 * Icon geometry, copied from Lucide (https://lucide.dev) - ISC License -
 * v0.510.0, the same icon set and version the product's frontend renders.
 *
 * Generated by reading lucide's own icon definitions, not hand-typed: each entry
 * is the inner markup of one icon, drawn inside the <svg> wrapper Icon.astro
 * provides (viewBox 0 0 24 24, fill none, stroke currentColor, stroke-width 2).
 * Deprecated names (loader-2, check-circle-2, ...) are resolved to the icon they
 * now re-export, so the keys stay the names the product's code imports.
 *
 * To add an icon: add its lucide name to the generator list and regenerate.
 */
export const ICONS: Record<string, string> = {
${entries.map(([n, i]) => `  '${n}': '${i.replace(/'/g, "\\'")}',`).join('\n')}
};
`;
fs.mkdirSync('src/lib', { recursive: true });
fs.writeFileSync('src/lib/icons.ts', out);
const sample = entries.find(([n]) => n === 'sparkles');
console.log('icons.ts:', entries.length, 'icons,', out.length, 'bytes');
console.log('sparkles ->', sample[1]);
